# Generated by Django 3.2.13 on 2022-05-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codersite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mickle',
            name='Email_id',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mickle',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mickle',
            name='subject',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mickle',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
