# Generated by Django 3.2.13 on 2022-05-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codersite', '0002_auto_20220510_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mickle',
            new_name='contact',
        ),
    ]
